### PR TITLE
i THINK that the itemrenderer should work now

### PR DESCRIPTION
**Pull request by notchyves**
i was playing around with baseactorrendercontext awhile ago but i had to update the sig for now. this code should work but let me know if it doesn't!

### CODE REVIEW

**Comment by FloppyDolphin57** [comment]
All you did was copy this from the Horion leak and delete the source file for some reason, I'm still get to see a good pull request from you on any project.

**Comment by ATXLtheAxolotl** [comment]
Uh also by the way amethyst doesn’t have a FindSignature function

**Comment by FloppyDolphin57** [comment]
LOL

**Comment by riesters** [comment]
https://tenor.com/view/salamaleikum-nebesa-visoki-cat-sleep-gif-26486949

**Comment by FrederoxDev** [comment]
> i THINK that the itemrenderer should work now
What part of it wasn't working for you? 

A: This PR is quite poor, you obviously haven't tested it. 
B: You have changed the parameters to be in the wrong order for windows **FROM** the correct order
C: Ctrl
V: Ctrl

**Comment by notchyves** [comment]
@FloppyDolphin @ATXLtheAxolotol I can assure you, this isn't copied from the horion base but from my codebase and it works for me fine but I understand if it doesn't work for amethyst. :D

**Comment by Intoprelised** [comment]
still a bad pr because it wont even build in amethyst

**Pull request closed without merging**
