### PR TITLE
Add missing parameter in Tessellator::begin

### PR DESCRIPTION
**Pull request by Intoprelised**

### CODE REVIEW

**Comment by FrederoxDev** [comment]
That parameter I couldn't see on the call stack for windows

**Comment by FrederoxDev** [comment]
Have you tested with the parameter?

**Comment by Intoprelised** [comment]
I have not tested it because I am not skilled enough to understand how to build Amethyst, but I can shortly. This can be found when decompiling the 1.20.50 version of the Android client which has RTTI, in a string you can see:
`void Tessellator::begin(const mce::PrimitiveMode, const int, const bool)`

I will test changing this bool shortly, there should be no negative side effects because I have it set to false by default, which is technically was before.

**Comment by FrederoxDev** [comment]
I can double check the call stack on windows when I go on next, but I'm pretty confident this param didn't make it to windows

**Comment by Intoprelised** [comment]
I understand what you mean and I do not see it used anywhere in IDA, I just find it unlikely that they would only add a parameter to one version of the game.

**Comment by Intoprelised** [comment]
It exists in the chinese version

**Comment by FrederoxDev** [comment]
I've seen quite a few times where parameters have been compiled out on windows. Also android has rtti? I thought it got removed, no?

**Comment by Intoprelised** [comment]
Android does still have RTTI, the chinese version is on windows and does have it in the symbol. As well as mBuildFaceData still existing in Tessellator it makes me feel that its likely the parameter exists but is not used.

**Comment by FrederoxDev** [comment]
Yup, just double checked windows and it's not passed

**Pull request closed without merging**
