### PR TITLE
Add ClientInstance::requestImageFromUrl()

### PR DESCRIPTION
**Pull request by CreeperG16**
Adds the `requestImageFromUrl` virtual function to `ClientInstance`
```cpp
std::shared_ptr<FileDataRequest> ClientInstance::requestImageFromUrl(const std::string& imageUrl, std::function<void(Bedrock::Http::Status, const Core::Path&, uint64_t)> callback);
```

### CODE REVIEW

**Comment by FloppyDolphin57** [comment]
What's the point of adding this if you don't add the class fields to use it lol

**Comment by FrederoxDev** [comment]
Wdym? He's shared him using it in the private discord and seems like he can use it just fine

**Review by FrederoxDev — APPROVED** [review]

**Comment by FloppyDolphin57** [comment]
> Wdym? He's shared him using it in the private discord and seems like he can use it just fine

The pull didn't include the struct of the return value of the function

**Comment by FrederoxDev** [comment]
Ah yeah

**Review by FrederoxDev — APPROVED** [review]
Only using the callback right now

**Pull request merged**
